/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* isrTimer */
#define isrTimer__INTC_CORTEXM4_ASSIGNED 1
#define isrTimer__INTC_CORTEXM4_PRIORITY 7u
#define isrTimer__INTC_NUMBER 90u
#define isrTimer_INTC_CORTEXM4_ASSIGNED 1
#define isrTimer_INTC_CORTEXM4_PRIORITY 7u
#define isrTimer_INTC_NUMBER 90u

/* ADC_1_IRQ */
#define ADC_1_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_1_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_1_IRQ__INTC_NUMBER 138u
#define ADC_1_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_1_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_1_IRQ_INTC_NUMBER 138u

/* WS_DMA_INT */
#define WS_DMA_INT__INTC_CORTEXM4_ASSIGNED 1
#define WS_DMA_INT__INTC_CORTEXM4_PRIORITY 7u
#define WS_DMA_INT__INTC_NUMBER 50u
#define WS_DMA_INT_INTC_CORTEXM4_ASSIGNED 1
#define WS_DMA_INT_INTC_CORTEXM4_PRIORITY 7u
#define WS_DMA_INT_INTC_NUMBER 50u

/* UART_SCB_IRQ */
#define UART_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM0P_MUX 8u
#define UART_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ__INTC_NUMBER 46u
#define UART_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM0P_MUX 8u
#define UART_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ_INTC_NUMBER 46u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr__INTC_CORTEXM0P_PRIORITY 3u
#define BLE_bless_isr__INTC_CORTEXM4_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM4_PRIORITY 6u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr_INTC_CORTEXM0P_PRIORITY 3u
#define BLE_bless_isr_INTC_CORTEXM4_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM4_PRIORITY 6u
#define BLE_bless_isr_INTC_NUMBER 24u

/* WS_SPI_SCB_IRQ */
#define WS_SPI_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define WS_SPI_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define WS_SPI_SCB_IRQ__INTC_NUMBER 47u
#define WS_SPI_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define WS_SPI_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define WS_SPI_SCB_IRQ_INTC_NUMBER 47u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
